version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devconnect
      POSTGRES_USER: devconnect
      POSTGRES_PASSWORD: devconnect
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devconnect
      SPRING_DATASOURCE_USERNAME: devconnect
      SPRING_DATASOURCE_PASSWORD: devconnect
      JWT_SECRET: changeme_change_in_prod_make_long
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
