name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # Temporary JWT secret for CI only. Rotate and store in GitHub Secrets for production.
      JWT_SECRET: 'devconnect-ci-temp-secret-please-rotate-CHANGE_ME'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & test
        run: |
          mvn -B -DskipTests=false -Djwt.secret="$JWT_SECRET" test

  docker-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set image name
        id: image
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}/devconnect:${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push image to GHCR
        run: |
          docker push $IMAGE_NAME

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.46.0_Linux-64bit.tar.gz | tar xz trivy
          sudo mv trivy /usr/local/bin/

      - name: Scan pushed image with Trivy
        env:
          TRIVY_SEVERITY: "HIGH,CRITICAL"
        run: |
          trivy image --exit-code 1 --severity $TRIVY_SEVERITY $IMAGE_NAME
