name: CI

# Grant explicit permissions to the GITHUB_TOKEN used by actions. Required for package publishing (GHCR).
permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # Temporary JWT secret for CI only. Rotate and store in GitHub Secrets for production.
      JWT_SECRET: 'devconnect-ci-temp-secret-please-rotate-CHANGE_ME'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & test
        run: |
          mvn -B -DskipTests=false -Djwt.secret="$JWT_SECRET" test

  docker-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set image name
        id: image
        run: |
          # Use lowercase repository path for Docker tag (Docker requires lowercase names)
          # Use shell to lower-case the value because GH expressions aren't expanded inside run blocks
          OWNER_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/${OWNER_REPO}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image (no push for PRs)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
          tags: ${{ env.IMAGE_NAME }}

      - name: Run Trivy scan (produce JSON report)
        run: |
          # Run Trivy as a container and write JSON report to workspace
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $GITHUB_WORKSPACE:/workspace \
            aquasec/trivy image \
              --format json \
              --output /workspace/trivy-report.json \
              --severity HIGH,CRITICAL \
              ${{ env.IMAGE_NAME }}
        shell: bash

      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

# note: cleaned YAML to remove NBSP characters and code fences (fixes GitHub Actions parser)
# timestamp: 2025-10-21

  mock-deploy:
    needs: docker-scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build package (skip tests)
        run: mvn -B -DskipTests package

      - name: Start application (background)
        run: |
          nohup java -jar target/devconnect-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          echo $! > app.pid
          # wait for startup (poll up to 60s)
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/actuator/health >/dev/null; then
              echo "app started"
              break
            fi
            sleep 2
          done

      - name: Smoke test
        run: |
          curl -sSf http://localhost:8080/actuator/health | jq . || (cat app.log && exit 1)
        shell: bash

      - name: Stop application
        run: |
          if [ -f app.pid ]; then
            kill "$(cat app.pid)" || true
          else
            pkill -f devconnect || true
          fi
        shell: bash
